### ISSUE TITLE
Artefact construction

### ISSUE THREAD

**Issue by daccordeon** [MatthewJA/blobmatch#38]
To do logistic regression, only need to run through feature_vectors.ipynb and logistic_regression.ipynb , all other files auxiliary.

**Comment by daccordeon** [comment]
I've added comments throughout and have tested everything.
@MatthewJA could you have a quick look at the directory structure and the README (I'm not asking you to download and run the thing) and give any urgent feedback. Sorry for not giving you much time (I understand if you don't respond within the day).
I have not started writing plots into report so I'm a bit worried that I might need something else, but I guess we'll see.

**Comment by MatthewJA** [comment]
You can/should put source/report/project/README.txt/LICENSE/.gitignore into the project root. No need for the artefact folder (since there's nothing outside the folder anyway).

I recommend making sure your README instructions work by running them yourself (somewhere else, so you don't accidentally break anything important).

**Comment by MatthewJA** [comment]
If you need more plots in the report, so it goes, make 'em afterwards. You won't get artefact marks for them but you should feel free to add more plots if you think it'll improve your report. You can't lose report marks for forgetting stuff in the artefact after all, probably [citation needed].

**Comment by daccordeon** [comment]
Great, thanks Matthew. I've gone through the README in a separate place, I think they hold.

I've got rid of the artefact folder.

I'm happy to close this issue.
