### ISSUE TITLE
Seminar title and abstract

### ISSUE THREAD

**Issue by chengsoonong** [MatthewJA/blobmatch#40]
@daccordeon to get @MatthewJA feedback by Friday 5pm.

**Comment by daccordeon** [comment]
Blobmatch: Machine learning for cross-identification of radio galaxy surveys
Success in cross-identification of radio galaxy surveys is determining the real, physical objects that we're looking at. The naivest measure of two sources (or blobs) being a match for an actual object is their separation on the sky. Using this separation, we train a logistic regression predictor on the TGSS and NVSS radio galaxy surveys to partition a patch of the sky into objects. Although this predictor successfully learns the importance of the separation, the naive partitioning fails to convincingly identify objects in the sky.

Happy to send this in for seminar, abstract will likely change for report proper

**Comment by MatthewJA** [comment]
- I suggest you say "radio-radio cross-identification" rather than just "cross-identification", as there is also e.g. radio-IR cross-identification
- Technically not everything in NVSS/TGSS is a "radio galaxy", just a "radio object"
- It would be good to add a quick line motivating the problem, i.e. why is radio-radio cross-identification hard/what kind of objects can't be cross-identified naïvely?
- Logistic regression doesn't partition, it just classifies. Be sure to not conflate the classifier with the partitioning: partitioning in this case is a decision you make based on the classifier.
- What is "the naive partitioning"? It's unclear from the abstract.
- Good conclusion that the partitioning is unsuccessful. Note that this might not have anything to do with your classifier!

HTH

**Comment by daccordeon** [comment]
Blobmatch: Machine learning for cross-identification of radio object surveys
Success in radio-radio cross-identification of radio object surveys is determining the real, physical objects that we're looking at. The naivest measure of two sources (or blobs) being a match for an actual object is their separation on the sky. Using this separation, we train a logistic regression classifier on the TGSS and NVSS radio object surveys. Then use its predictions to partition a patch of the sky into objects, by transitively grouping any chain of predicted matches. Although the classifier successfully learns the importance of separation, we find that the naive partitioning fails to convincingly identify objects in the sky.

Let me know, and I will send it off to Bonilla.

**Comment by MatthewJA** [comment]
- You can just say "radio surveys"
- Rest sounds good!

**Comment by daccordeon** [comment]
Sent to Bonilla:

Blobmatch: Machine learning for cross-identification of radio surveys
Success in radio-radio survey cross-identification is determining the real, physical objects that we're looking at. The naivest measure of two sources (or blobs) being a match for an actual object is their separation on the sky. Using this separation, we train a logistic regression classifier on the TGSS and NVSS radio surveys. Then use its predictions to partition a patch of the sky into objects, by transitively grouping any chain of predicted matches. Although the classifier successfully learns the importance of separation, we find that the naive partitioning fails to convincingly identify objects in the sky.
